<?php
    $tweets = $block->searchTweets();
?>
<?php foreach ($tweets as $tweet){ ?>
    <p class="tweet">
        <a href="<?php echo $tweet->user->url; ?>">
            <img src="<?php echo $tweet->user->profile_image_url; ?>" alt="profile">
        </a>
        <b>Created: </b><?php echo $tweet->created_at; ?>
        <br />
        <br />
        <a href="<?php echo isset($tweet->entities->urls[0]->url) ? $tweet->entities->urls[0]->url : "#"; ?>" target="_blank"><?php echo $tweet->text;?></a>
    </p>
    <hr />
<?php } ?>